#ENC[AES256_GCM,data:TklApbLomCnwKBAka98rVHOe65L44TfL+r8TVrgSL2lzD9+/qzmh08GO,iv:XBbz91zIpbQIkUG7yS9zngcG2kzabtWw9481efFpT1w=,tag:yC5zmU3tLuu9CXNoF465WQ==,type:comment]
#
#ENC[AES256_GCM,data:chLhOAUFLVV8e+66TaVJzkRQSQ1BgGAStmRS/1cu60W20wIdLC9+3+Omi5OYs2T795/HgTfyBSbKaA==,iv:ozDzvgUA2cH/THOT3PUouQ7zk0sd4KCdQU1ZiKgxEo4=,tag:7WZFbtDQGzdgUOOCsAaEBQ==,type:comment]
#ENC[AES256_GCM,data:7FQDI+CKvhGhC/kpmYrgyr+VkeSxq6FM8f+b81eD+X7oyt1fiBoUzmX77Q==,iv:5iYDfXh2pMtBrCG36gvSigMghXf1FQBB1M+WhJSqRn8=,tag:4tqnE2jJdTNxMEe5HRtm+g==,type:comment]
#ENC[AES256_GCM,data:CTLhoU90YD1SSW2rHUP8jqrH4QcAToIFfZ68pSsBy2m01pphL9S8QZih50/u/+AyYMYiiaBwtEQt,iv:lKWyBqDHlIZNtQCc/5W/AeftTJeHWKLjGLWNylD0iNY=,tag:MOP0t6qqp+oz4h/MXE16nQ==,type:comment]
#
#ENC[AES256_GCM,data:0y2DPON3AW89S3hQgOWFge+Lurw/KUbdCm8+Lw3QNcT4p5YBqBByzGWH5B38v1s4NxMNp+xHb2uiGw1NKw==,iv:HW2oOCZ4cz1SQBhk+gG0UcqYkL6ofxY6gwAB21HEU4Y=,tag:zgEpZfUmu0xmNi5ESbzRZw==,type:comment]
#ENC[AES256_GCM,data:XChAhVnGjLvcQa4O09idgaMYYdMYRw+uT0oPDs0=,iv:anmAtDRXZgHmFkuMLJID1RVMLH3HeElPET0sVQZ6rrY=,tag:0txIRyf6A+p1VSbl11KqoQ==,type:comment]
pppoe_username: ENC[AES256_GCM,data:fytnQ8PcqYY1cbHw/4o=,iv:WiC7wd/72Hi0zeOOdxNGg1HrvoFlv1wyTWv0aV05b3k=,tag:5QZ8Qa08WzUgedBzkZ/8Qg==,type:str]
pppoe_password: ENC[AES256_GCM,data:iqbXCTKfxIE=,iv:Tj/C+uIPBRLODGGKM5GL0JezRsPDgY1/BYYnWM9NTgY=,tag:FniC85L2x1wqTrwNZwbJzg==,type:str]
#ENC[AES256_GCM,data:jmBCjb8RvdQFAuSEMvoPp4ql/X3ctpDbHA==,iv:7+gli331rlEJcL0udJswHP5u9xw2IZAelT7k5UbPC6E=,tag:wcC+UkKM40Vjpzfav9WlEw==,type:comment]
wifi_password: ENC[AES256_GCM,data:T4m45pvamICcTSCo,iv:gvWqkuA6gApOwimjdd5BdMW4QJ1Sy49LwNHexSuiGco=,tag:15kQy3B13VKZJpk0mUwLzQ==,type:str]
#ENC[AES256_GCM,data:5wtlIO99BUfMRe4VF9D1WVBGnO5dbxXECDFIDJ7Iyvf0p+CBhiP7OZx9N2mADN8eig==,iv:Kl9cfgDrCWybtpopYAogb+WN+UZ0DgRoJGYYxAiuFtI=,tag:N8PDSjb1jejcWmGd6ZR7tQ==,type:comment]
wan_macaddr: ENC[AES256_GCM,data:3SRBgnVWxqd69KfL2cZVb18=,iv:2z1ivX8ZSwaCDttq/zcklhhH1AOP8zihQYl6vBKAiZY=,tag:J0QOFpiFIqjw2bCKW1CTrQ==,type:str]
#ENC[AES256_GCM,data:EMBHfuUcUC2zD4f7fafVGtWb6R7LXjQ2rRFk83XnLQ==,iv:Fhhpi6TqnLDLNdQYgr81O5VYgpghSWHT1h9HVvtlkOo=,tag:33go6bv8c8nUDR7S0wFaZg==,type:comment]
he_tunnel:
    server_ipv4: ENC[AES256_GCM,data:/gGyJ7htwLtwhwtd,iv:P+jfWDVrSy6rcwJ8nWUO1WHMlPbeIlh+WFzBxwHAtKc=,tag:UPJ1SR/Cv3gPr02Hce3/lA==,type:str]
    client_ipv6: ENC[AES256_GCM,data:cMNH5D2usgfVr99CwBIl/Vt9o5CYhQ==,iv:Wr4n44PCb16q+Xgf0/G1zvY/jXFmTyS6OXsfU7a5F+0=,tag:SH3FGLPnQL7KbHUIK2Lgtw==,type:str]
    tunnel_id: ENC[AES256_GCM,data:qkC+Xx2A,iv:7HLmjueWg6ooKOo9hNCdRM74SWwpT1tEVQzSgif8VSs=,tag:gHiSusoj1Sr9BQX07cNrKA==,type:str]
    username: ENC[AES256_GCM,data:lexaPF3fIStRjIw8HPX4KA==,iv:ypbSdwvsWHgkmzi/ttqo3U8tbiZVrQcSXfKFrb5PWOw=,tag:6ClWdwhZT9eyhRX1IenizQ==,type:str]
    update_key: ENC[AES256_GCM,data:ZnindcIJgmbzIVtnLWT+Mg==,iv:RAojMlvMhLfbJ8TZ/RfZHDz0QnbGlRuH0kxDh5fUdQw=,tag:3/Q0XmQaRulGIk/cWiw02Q==,type:str]
    routed_prefixes:
        - ENC[AES256_GCM,data:LarEkp/Y8lxYBUcZCaR4F/cXEQ/0,iv:gGk3tgqLN8b+7Nc26GKdN5sJTgB/5n/V+09dSp/dA8s=,tag:kMiqAb89UziAYrtj0PqT9w==,type:str]
        - ENC[AES256_GCM,data:UDeMAc6sCbbwBvLR70QUEepo,iv:HFYhtEIh61GbJUuCzDMhTghlK8jPTW22zVvBz1HFsTE=,tag:/Z224HfPN3zjRb5jtfR/Mg==,type:str]
#ENC[AES256_GCM,data:9qta81RmxSRn2VoXITs=,iv:eI23ARcE6G/RfdLBhOxwa5it2VwWl1XeTpimLdiwaU0=,tag:WpoN6QKhugUFCmvWEofyxA==,type:comment]
wireguard:
    #ENC[AES256_GCM,data:1UTglxqdTGDKJf83zsnYC/oTspx/EmiTbUhfjO7uKQC+iJOorhsJdq36Sc6WPQ==,iv:ySPL5Efwoa7c8o/SNdmP0Bhn4nIHErF9FCm/sDSqTCA=,tag:4YDAGnIbdW5SjljSnY4Adg==,type:comment]
    private_key: ENC[AES256_GCM,data:1tsRS6GDOb2t1Vjn6TkiXb/0TGqvlVB2THBcOJ1g+ADN18IeoATPNre+/jE=,iv:M0c8FY+pkV/Dd38GzPhtfYrbWugZQ0itywQUvs1dFZ8=,tag:esFWWeStyUAsOArByid0Lw==,type:str]
    #ENC[AES256_GCM,data:AOS5hQBaL1NMSgJf1oc16TIrRxUhX0PhxvFX98bVY63dO/LrHIJTX4BNRj4b7lRqOUcAiw7avXKHR6+RDHsj,iv:l6J/0jccalIYNOcfv278/mL5+WM4iQBcrbyB+DWHg3s=,tag:NDnq4fT3LrzjslwGxl+HuQ==,type:comment]
    public_key: ENC[AES256_GCM,data:gTtKY31iCtZogY9iPfLGvrV84J0JX3xzUXX/Mid9Fo0BHMRsg3KGaZJIHtc=,iv:qQZmHR6+6LFlhRusjp9FnAFl1X9NtdIHB6IBpECqr7Q=,tag:Vbka6z2zuh5RYZdZ25iLag==,type:str]
    listen_port: ENC[AES256_GCM,data:Y1bIBRs=,iv:Z7mEdm30fxfmu0yPVi61NgLzSpcZHLvCcCbGGJuUmLA=,tag:Wxzw4cd6GqrsjU4sZnqtNQ==,type:int]
    #ENC[AES256_GCM,data:q91uRUTkcKLhug==,iv:d0Y+NL9kHblA8e7ZpA3onqWzRPBNmAAdhR4yrQ/qdXw=,tag:phzBhIhKO0gZiAoSohAF7Q==,type:comment]
    peers:
        - name: ENC[AES256_GCM,data:0BSVF6mHgdzWOwV4HBrRMg==,iv:6wZ3kCHLkWlkDWcvGDEFAqtJ9nz2AHy5XCQJb1fmFEE=,tag:iw92kr3pL+1n4zyPsCGjhg==,type:str]
          public_key: ENC[AES256_GCM,data:dOjvafsgawC8Jhcm76kvcm2m/r6V3/AFVjzuQoG9q+O5TFoT5n9wS2JISzY=,iv:TzuXH2FgJPs7yBKDiuVdtWEbLFtjJHMBpztaXfftOB4=,tag:e01JbRDZfCm7UzREWim/vg==,type:str]
          allowed_ips: ENC[AES256_GCM,data:7gg9mcrY/bvjiox0dA==,iv:b9Xdz0gg3ot685bs2zWrWgjFmaKrmswf8SVw3jdQzWI=,tag:zJ6ZSiMczgpl5C8xAQkO6A==,type:str]
          #ENC[AES256_GCM,data:7xSEq4AkpDRtH/S063g/H/jJxUD1fL+vcTnkLUqH,iv:80io2KjMdfQ9aaM+17/J3xP9ZHlhhSwaZsAyyYfummE=,tag:CYJOAvCyxgjIlW0F8mnAqQ==,type:comment]
          private_key: ENC[AES256_GCM,data:8wl9MG5GvlSGySjwUrrMUHtGvT54v8VGu32fCEUunY9bIvkjtXHD0s7/Ii4=,iv:Nygbo20advdPdliSHmPw/F9DIJZfylt1Bu+IfvQiYLM=,tag:tYlETFNZk0GYf+ZoGUcXaw==,type:str]
        - name: ENC[AES256_GCM,data:ONF/x2bJDNJm1oEqww==,iv:k5awaSzWWN+aVaaxhiJRqioUl7vy+hmGTSav1GpLvq4=,tag:U1yjtxCOHkdXT8uHJ0Davw==,type:str]
          public_key: ENC[AES256_GCM,data:oq27spqMpJfXqIJ8utfuF+sok7YP0KG5Mx1z/AbrZnkxjXYamvDy9Vhl6hw=,iv:bF45sJAW6ZFyISEzEUnrMFtIvF8hop1Boz51BvmYoSE=,tag:4E9mSGoFD24xxGYSKROykQ==,type:str]
          allowed_ips: ENC[AES256_GCM,data:lp/I8kQWPne9BM8RiA==,iv:+5DkoZGQyc8zc96Q6a330yqrpH25sHB3W9ZyotD+580=,tag:RQcgv6N3vmyGQMFz2jNozQ==,type:str]
          private_key: ENC[AES256_GCM,data:vyfJ0u54/Du4R2r1broltFVbgMxJZRoncKewuxhs5F6QNm7hAH/u3pYSHDM=,iv:T6E6Kp04ELavPYeS2a146qh5UqGsXvnvorlfsl6CaeQ=,tag:pQwtod3pdzXEWUeZ0Ymiyg==,type:str]
#ENC[AES256_GCM,data:PlKNXmRCGZNxhDSE2KAyqg==,iv:2j1KedoPwodVL1VT8uDh4iQPAAxx6VOgbCnAYyCM49I=,tag:71UPQIa0A1WynGBJTiqM9g==,type:comment]
ovh_ddns:
    zone: ENC[AES256_GCM,data:QMja9CL037bajYzByQ==,iv:rlGQSAC9hc34y4tmISIQSG/9E4/XRfpb3emTgn0wveU=,tag:RMZ0J2Eku4zSl3VGMAHcRg==,type:str]
    #ENC[AES256_GCM,data:bhqWxnqbSjgHNe6LJwioebO8yacMxA==,iv:JYxxVai7NHjvsNoL2CSnqw/MO8ujf6SPzD3HiHBfFNM=,tag:MhM+8lshRoE06Yx4o6xe3w==,type:comment]
    subdomain: ""
    application_key: ENC[AES256_GCM,data:TLAIJ2MsmLr97bK9Cmrz0A==,iv:XLcScvtSiIDkpQXqJ6U0YfIiS02htVY5aEdSHgdjGkM=,tag:PFxpVFXN8ywc81VqH732Lg==,type:str]
    application_secret: ENC[AES256_GCM,data:qvdg1BsihzlpnT0s8sF2rw2OnKab0uPmcta/Ktx4VYc=,iv:T261KLMFU3paLcyhQLIfCs2ozP6GjREGBXNJqOdSZhU=,tag:NtbfVYC3+WJgJBkpl1qtbg==,type:str]
    consumer_key: ENC[AES256_GCM,data:y3Y7E5W4sSAQw79s/gyjn3XIZ+59fYscgSTGjf0wpjU=,iv:5LV6ROHoNeB+Yunrx7ceo1QudK1xdJWv8VGqiFnTrW4=,tag:HGlQfzjRTJuyOPS35hiRaQ==,type:str]
sops:
    age:
        - recipient: age1w8lcex3r5geeuxuvdfdvdjwm5y6djv7vwd7rqdj6awzpme8wc49qltgxgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3REh6N2xBL0cwU2t4bTBk
            NzhoQWFVeVpFOU5Sd3VBTHdWei9WSCs1Z2hJCnFSL0R1UUVYSEt6ZVhGYnhUekZF
            bkppNDJRZDM1SWU5b0pFQWYvQ1M5eXMKLS0tIEJQN0ZqVVpvaTRYbEM1eGQvY3c0
            dGZOM0oxR0xYUlBnSVNnTkFzSENiWVUKQxQr+vl4PVk0A778kGfnqApoenKQktHC
            chqkf8yL/A8mRySVF3xcQckTBZGkzyhxJaavVmyA74qTEDAGkLmgww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T12:47:35Z"
    mac: ENC[AES256_GCM,data:lWd0uEDAZ3r0PEStB3BYZoV+Vof1oSZdg6e4HPhIXhr2iqxq3QIaxNJ4bVbvrs8HnbHUP3PRfjri4yaqCOGIGbl1QWLOs3oPlMeyUVeTy0DF1mObudjdxn9Ke417Uj1rBpsMNr6SjVCv9tL2FKmsa1cvxCpzU1AWcDJ5wQkX5X0=,iv:FIAvIfk0SC/4BfzNMEXIyCIymUN8OKv51ig3M4M+lHA=,tag:mn/eDdyfSrW49N6V8WjQLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
