#ENC[AES256_GCM,data:jZ1V1lzdhMYNwobuzkYaCF3MpTLQR5mCqcvlTQNVA+LeYGo9mwgQyUbZ,iv:+rwY2gLgxcuAK5B+MCn85LDIJrB7zrrOWNCpLf2zQUU=,tag:NS6BGZPOnSg9iBRYPV/txQ==,type:comment]
#
#ENC[AES256_GCM,data:5SkE1fopMpzJ9EltfYZ70PsazFVg2AWdG3XTw/u0FerlGQot1lAfiikT5+ytTNcXInr++ty0t6RB5w==,iv:3hvimvWpSfLJ2BKvV3/KlwH7WNGpJ6FXL9yRjfLyUa4=,tag:JOSL0YRMbzFb7oeteBOMiw==,type:comment]
#ENC[AES256_GCM,data:bl6PX1pqMmqHUJLlL9OZOVgedjGgwY5P1TsV4nG5ldebodqOoQS95Bsw4w==,iv:IQ8/UQEe4WAFkV3P9vCNryiD8O7mA2BkCcfBBuREGE4=,tag:AxokANpPqBx7DG0XAH4McA==,type:comment]
#ENC[AES256_GCM,data:ZaOPQgSETPAy+t8PDwv98FgxP5bTV+Zx7kR4OposumIE8HDJ1qd4Z6IMNzlL2ZxFMTD1HxN0Snd0,iv:8o+3oLrq6Z4oiBvlavEOyzmo5pNU4gf6BUfkZSaHsCc=,tag:4Pui+5Sq4r43YsLVgU+FGQ==,type:comment]
#
#ENC[AES256_GCM,data:VxW+0WPrd6qFH1eA/aybCDWwNgegxM4oY2P2jmqJXA/DsKmE4OxT8TYujiiDDDk9uh4ZGeRp0KUeG9biNw==,iv:VqqsFZAeTWZ4w1RMEM/IjOHhgRa+Apm/ZG/yjRtcfWg=,tag:XEAoWTG9999+RE0oFg8JRw==,type:comment]
#ENC[AES256_GCM,data:ZQkGd5cDBSY1QLTU9rg0JLhNYADzwuh5GbGhVGs=,iv:4Xdzj4W+2ml6dcK+q4Gqg4dMlWLSmz8wfsvBVWMRTT0=,tag:5343dyZGyMOcIgrDOcy7jQ==,type:comment]
pppoe_username: ENC[AES256_GCM,data:gmhCsfYoZWuIHuAMwv0=,iv:lwXuRkhyz8RK9wzsA3ASEUB47r16NCcFLJq4RMeWN38=,tag:LlcMoalSWNbxes8xbLyDCQ==,type:str]
pppoe_password: ENC[AES256_GCM,data:pYhtPNluiWg=,iv:1H5Ea5yRkBlYEFts7PT8UMPgHcA4+RXy/vp1oj3paAk=,tag:dT9QPNzehWJokW6iXrS3PA==,type:str]
#ENC[AES256_GCM,data:J6rFV9w/d8BDnPGCyKQaLMzuLNwHze+HBQ==,iv:vvL3y69ttqaUQjnXM3oHVFGJZaBo5eloNvyk2URXHtw=,tag:EcDfL07mKH49baP4N/mKAA==,type:comment]
wifi_password: ENC[AES256_GCM,data:3eKGGq76/4j9ZRiu,iv:ywMaJpossA93lyNhDMD1c1dtZouG69cHoIOeIPbxKSM=,tag:NYT5zU7ffibL8seEOFOytA==,type:str]
#ENC[AES256_GCM,data:iFlfGx26nu3z7eGnlMMWLB2GvcIVrmubjLDnzh8w0lgKmNwIkfqzt5tLA8U7pWCnbw==,iv:MKNCtUjnR8d5IXTmlLx3XEk2n76viAMBCYHCstSLxlo=,tag:x8SiBzr2YaR7HLkLWb8Yuw==,type:comment]
wan_macaddr: ENC[AES256_GCM,data:TJ6oUSRiQWkIeGOonWXiC5I=,iv:isJSpQAgCVH4sqq2neolM2cZjQ+OiRb4QcxtXOEiU4Y=,tag:EiGWWFRcHEwa/aCXq+/FOA==,type:str]
#ENC[AES256_GCM,data:UWTV3a0hrWuQYHEv9477JCETIpi/opNFMNXa+I8ADQ==,iv:uhQka2uMaTyXqdClUFrx9th3rFTShXC6Rd+PJX5Qi30=,tag:tbHHYhE1TaSdJtWXSXjNIw==,type:comment]
he_tunnel:
    server_ipv4: ENC[AES256_GCM,data:L8EbqO5BRmZc9Pfu,iv:2b3ADxOGUE0Wly6wxFuKjtw9tF0jM11ihDYMpoh2trQ=,tag:fWWEOmXW0LwdbSm26K7Skg==,type:str]
    client_ipv6: ENC[AES256_GCM,data:xjenaWW+U4DNI7MXQXlj3+GCAuAYvA==,iv:lHrwCloG/rhZRjUreXwXJZkYasrvNbKcLo+En5C5Q7A=,tag:b+DbCv/nZSuZLvMgn4ZEzQ==,type:str]
    tunnel_id: ENC[AES256_GCM,data:q/DHOZyG,iv:Q12PIU0km2mKePp+sCe0idPv6U8SUrWXYDwrg5gvMDE=,tag:VEwO1w5sjLoN58ReX86q0Q==,type:str]
    username: ENC[AES256_GCM,data:zRdrj1MVaVMf23SKFdCtmw==,iv:PKqM0BRfRmWU7oieRsF7dEI6HtW/QA6pLahQImC44uQ=,tag:cgcRXTUNrlTS3zl0Fd1T9w==,type:str]
    update_key: ENC[AES256_GCM,data:vMMXnokZ2M1woxruyPmh6A==,iv:8+nWFUMff5LInFwJg/K3KAsT28AfYW+7JYp+5ZKVyKk=,tag:jrMzB6Tv/FOzAqAo9FKUWw==,type:str]
    routed_prefixes:
        - ENC[AES256_GCM,data:cxDEFd7FdD9UAmtDmJOadopcSBSz,iv:rBgpW/FK0Thp+RjCA2XLz/ItY5UltCHG9aXNIHygkRQ=,tag:1lCsWRKQv4dIsHuGjEnsgA==,type:str]
        - ENC[AES256_GCM,data:kGYCpzSnXJyKFPeYaLR5KWaM,iv:EYpecLMETYhjg4eh2nW3YSAyWBeo42Fg8xMN91fDj/g=,tag:ROIJMWtn28ApRP8O9TXyrA==,type:str]
#ENC[AES256_GCM,data:tnIoiiGMZ3OrzsqfBnU=,iv:SAmN6jJIoqiNSi7JGyJYvddNLWzqTNeSRCruaDsB8Zg=,tag:Jlt6OCPtsEW6ZgpEJCwczA==,type:comment]
wireguard:
    #ENC[AES256_GCM,data:bB7zcsT8xRYKh18Wv/c8gZ8ZNkiSJQZ8FCaLddJDP8crTnCPYNiILat/KxvOmQ==,iv:AOQJosX15dvxeA8uRaa9Qswz3Tvo8QrWPMtliyHLM9w=,tag:eDX2DE1Dh31zANxTS38dPw==,type:comment]
    private_key: ENC[AES256_GCM,data:wmwip+h8CBBbS4SANDOTU0nva3yxD3sA7uQz,iv:SrLx0WZ+uZFHVvo+k6czPJ28OoBn4bZXiKROFUtt4mQ=,tag:fb6VBDVYldU+4EcuTWdyyA==,type:str]
    #ENC[AES256_GCM,data:jmfALjcESMbTJ3SjM/36limXBKq3jbmjoQQ8nnhR7mbMC+KDwqzZ7sp7E1mAtP+3GxZ2cflwbLwTxlkqXW2b,iv:guCULE0by+O04RdkLwOswoEi+LlfzxVKYAgA4UnRe78=,tag:V05lBE7nAxcHhzSeBJdaYQ==,type:comment]
    public_key: ENC[AES256_GCM,data:CCeJZCWgM4I0MmbtI6n0P1nVEKnNzh5rGg8=,iv:WZEYmhQ42ON9O5I80/SpZH5WP1obttZRsoDplZ88LBE=,tag:8jPEyH6J14Kska7ElGA7gw==,type:str]
    listen_port: ENC[AES256_GCM,data:d6rDyvA=,iv:eN0UmoRqLWV4qYZpNkK4stXq5cVer5ARhn0mR/SiDQo=,tag:qddaIHbPNx67YllMC12V5Q==,type:int]
    #ENC[AES256_GCM,data:lrGD3w0LRqxbcg==,iv:h8auga1nQ0VX5xK5I7XT+p4FY7U+DVHypKT+OylqCZY=,tag:33zruUgTomlIZhSnSOfPWg==,type:comment]
    peers:
        - name: ENC[AES256_GCM,data:4qQSPSEzYS+XVa6Qhza0sQ==,iv:74Yxpl78WcsUhGDoFUFbnr20yHtfGbwnTQMOGOeJVlU=,tag:zAFkNM1hIXBWTa5Yfkm3WA==,type:str]
          public_key: ENC[AES256_GCM,data:lLLN3Bq4x1+PsCdUCYaXIDl/UCmppsaJ32TWsg==,iv:xg6wYJKi7jTK93ie6mIX9kjmPZryEAOJdzomw553v9A=,tag:4ddDKYYMqRqdeUpzWvt1SA==,type:str]
          allowed_ips: ENC[AES256_GCM,data:W9hJrnVQdWn0/HtmqA==,iv:XwJFqTN1nMNgrlbV0+iLQdHEY/gD0I0eoZXKKdi64Ek=,tag:g9zshEzApHYhNLl0gCld5Q==,type:str]
          #ENC[AES256_GCM,data:X52xv/6O92Go6l4+SeB8je72WLlrqsPA6NKPPXiD,iv:imZnMK4jwmDtJQgn8+3aUaQmVWly81a0yTKCf93bmhI=,tag:KeaLkeqbkA8bFGDj30V9MA==,type:comment]
        - name: ENC[AES256_GCM,data:tptK6x85N6BsTvtvwQ==,iv:HS0doSHhxnrEb7D4LYPEqfwAcgbbMNZFIYAQhALPDDs=,tag:kA/7xO+pzug6uVYud4uMEQ==,type:str]
          public_key: ENC[AES256_GCM,data:rBSvp6TYtTi8+FAUxM+I3DAdtfuGx4wpseEQKw==,iv:KrOsL703F3fldSdzEnQf4rlyeR+wOOYkTZ4S220s8eA=,tag:ShuFDT+djXCUWf5N9c2PyA==,type:str]
          allowed_ips: ENC[AES256_GCM,data:HXz91NFqgpQOvDvSdQ==,iv:unkx4dGoxz26ad0cYBgFQUpnLzRmY0Z/bNS02MiXnXs=,tag:SnhnRJmvxNUxdmLocrY6lw==,type:str]
        - name: ENC[AES256_GCM,data:RmnYREE=,iv:N4Gc3lAie45CW4bAxYSzKE9OqHTrEBmXmUkJs97qJ9g=,tag:iAnbSBfCJ39IWFd4csTJmg==,type:str]
          public_key: ENC[AES256_GCM,data:D/BPakCN0bS4YdIKgKY8io9YP1HnlWagsoLs0Q==,iv:2yWHqTY03/9SEYAXMNPHtAdABgJYuG/zuNJYdOdv6a0=,tag:nbGOHUtmsaoYG0roa8w6dQ==,type:str]
          allowed_ips: ENC[AES256_GCM,data:aNuKXAs1r7TztoUWZw==,iv:iGu5zGZ/Z6lwvGPLstKgRM6GqbyO+Q4Ex8p/FTePflU=,tag:j3FDFcvMOsWMo6I/sywsbg==,type:str]
#ENC[AES256_GCM,data:nGoIiJo+bezFEdEdKAdWag==,iv:aBZzBEDbGxrl0vIWs0cdOD+i0dd+lb/75CahRNGbXyY=,tag:zFBjQFPcvTd9ZyuekQW8sA==,type:comment]
ovh_ddns:
    zone: ENC[AES256_GCM,data:TDWhSBVYprBtuwoLUA==,iv:Iyi5Si98IxmEXopRMiRQ+KhEBUf+Waf+dbGX1mnEH3M=,tag:rYEwEUxKpWH2LIL7BAd0kw==,type:str]
    #ENC[AES256_GCM,data:BDCicbqzDtPPs3vO54ddgMwJSKJXNA==,iv:i0vQwek9HoyMh0vqJLRlp1r9TNIgJVdRwCYHTPzZ5gQ=,tag:wjjC4EQUU2TbdBWG+0Amzw==,type:comment]
    subdomain: ""
    application_key: ENC[AES256_GCM,data:jD7BG14AiOvKAJHFqlcwHA==,iv:hWH68NZzQn2Boa/zBIM0GAgyJJTFAWDNanlH4ckKPHI=,tag:GcOPVEPBP07lkt5iBC/yrg==,type:str]
    application_secret: ENC[AES256_GCM,data:6xlc3yscdlyLwo7fvkDfaA1aDh4cq+lzNqKdqKiouKA=,iv:htAl4QY/UPt3pmwIc7xpS+eHVVZkgVP3e5EoD7gmpww=,tag:GMTJpwXhPin53/6gH+P0YA==,type:str]
    consumer_key: ENC[AES256_GCM,data:YUtQZ9MKhmt5+iFGpdsHPTIndpl/L5wA+P1sYZfzUlQ=,iv:x92/5bxk7DecgsgKnMmTeussqVdkHCyN8EF/Agapszc=,tag:GG1kIt1IVlQx5715FXOKYA==,type:str]
sops:
    age:
        - recipient: age1w8lcex3r5geeuxuvdfdvdjwm5y6djv7vwd7rqdj6awzpme8wc49qltgxgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMmRFRmJmK0QzclNsQyt4
            UzJnSFNraDlOdjdkNm5VdmlzcHkrKzlkMlZVCnplZCtQVnhMSGRQV2wvS0lKVWxp
            UURYcGdqaTFGd2VPNDVSK1hSRTdEb1kKLS0tIHdQUXlzRTFWQlpRdkZabU1KbFE4
            eTVRS3B3eGVJUzM5NDNoZUdGNldad2sKkyYvKVbx442fGwVzf2LTNK1SGkr3oei0
            wAJuWpn0eAwmOkcTGbtKetJ7jk2dawX/PDadcl+lIu6m76fQugrIvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T12:20:44Z"
    mac: ENC[AES256_GCM,data:bd3wXWzNgNCmJKXEi+akvkz6rahbUnfn+VHPxkUJZVHZdw7JBqt25k3KRsjMB7naGFN/XkrYmdVsX/lnULZ1LQizAvfgUnjFLCnSqNyCdS5XuJp86DY95QJB1L/WE6qGD8elH0iq4uzhoMfdeCM4nctgSFWSeMkBcRmVSTKEsOA=,iv:Htt5SLf0lOtAxHvRS+iUGtcx5azz7QcByWa/gHQgi9Q=,tag:FA0MIr4Jv1vby7t9CnTaRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
