apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- longhorn-kustomization.yaml
- gateway-api-crds-kustomization.yaml
- cilium-kustomization.yaml
- gateway-kustomization.yaml
- loki-kustomization.yaml
- mimir-kustomization.yaml
