apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:U5nxSLA=,iv:mCl8tN9x0WTmAg3MCbWSV6JuyxmX3TxaECqu3pQgQlQ=,tag:Jjyu0ogaspMtuzcw4q3v7A==,type:str]
    admin-password: ENC[AES256_GCM,data:Nkj/KHE=,iv:g9XvJMeEOh17cHZuEss0vuW9gxkevwkoZv//yK2WzhY=,tag:espOoWuniFuPH0K1OSSKXw==,type:str]
sops:
    age:
        - recipient: age1w8lcex3r5geeuxuvdfdvdjwm5y6djv7vwd7rqdj6awzpme8wc49qltgxgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVFRURUpMNkhvSVl4N0Uz
            ZGpVU3p2bzA4L2tRL0o3bjJuenRKVzE5UGtFCk9WdVhMZUphNENpemNWTTdFckpI
            WTc1L1ZYWWpjV3hQc2hYdktKWmdsWEEKLS0tIDRZaXVtMzBXTTRxYzNzV2FIQmVS
            YUFWSC90eU1VR1pydmlRN0VUZ0NzQmsKLQkwlJG+Py4ausO6u0Ig5qKZs5V2PnE+
            bQumxwvhuuHKpLu0j4Dbct4ZSJm1dASQjUrb6SK79xfIoRPqQ2RKFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T19:49:26Z"
    mac: ENC[AES256_GCM,data:jbSEaDnd+etwojmBV1+NysasOEuMXfNBlz0tgV7cWnWhMYnM4iQ1bCPpN8+QsKzBdckxA9dviW7S7Tc7QtFqEUwQMEs/yZsUMKrPE/P8uPjf3WbRL3PpHbCgJuC6PGmIYSwKS2OuL4ZsnIP1RJ+ZyH+lorfRFvlrW20BuwDWKhE=,iv:pPn/JsSDy9YR7lDgicZblPhrUm3AfuOR24oe/tRJPR4=,tag:wU5vNSgWp8x9QPNnHoa2cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
